### ISSUE TITLE
Tableau Dataclass Use Incompatible with Python 3.11

### ISSUE THREAD

**Issue by wkeifenheim** [MetaphorData/connectors#827]
Running the Tableau crawler in a Python 3.11 environment & `metaphor-connectors==0.13.158` yields the following error on startup:

```shell
Traceback (most recent call last):
  File "/usr/local/bin/metaphor", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/metaphor/__main__.py", line 30, in main
    package_main = getattr(import_module(f"metaphor.{args.name}"), "main", None)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/site-packages/metaphor/tableau/__init__.py", line 2, in <module>
    from metaphor.tableau.extractor import TableauExtractor
  File "/usr/local/lib/python3.11/site-packages/metaphor/tableau/extractor.py", line 49, in <module>
    from metaphor.tableau.config import PERSONAL_SPACE_PROJECT_NAME, TableauRunConfig
  File "/usr/local/lib/python3.11/site-packages/metaphor/tableau/config.py", line 43, in <module>
    @dataclass(config=ConnectorConfig)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/dataclasses.py", line 225, in create_dataclass
    cls = dataclasses.dataclass(  # type: ignore[call-overload]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'metaphor.tableau.config.TableauProjectConfig'> for field projects_filter is not allowed: use default_factory
```

Switching to Python 3.10 works without error. I have deployed using Python 3.10 since that currently works, but figured I would post this issue as the [pyproject.toml](https://github.com/MetaphorData/connectors/blob/main/pyproject.toml) file targets support for Python versions < 3.12.

I did not attempt running any newer versions than 0.13.158 since that is the most recent with any changes to the Tableau crawler specifically.

**Comment by wkeifenheim** [comment]
Looks like this is the culprit https://docs.python.org/3/whatsnew/3.11.html#dataclasses

**Comment by mars-lan** [comment]
Thanks for reporting. We'll work on Python 3.11 compatibility.

**Comment by usefulalgorithm** [comment]
Hi @wkeifenheim , thanks again for raising this issue, it is fixed in the latest version.\
